server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
         google:
           client-id: 575121414306-tgbhfd7sst3mo4avhankt28abs7msbrk.apps.googleusercontent.com
           client-secret: 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
           scope:
            - email
            - profile
            
         facebook:
           client-id: 424998039346475
           client-secret: 9c5e1090b0b079eee37d9e40e036785b
           scope:
            - email
            - public_profile
            
          